import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Pic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Transition from "@/components/Transition";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className="flex items-center text-black w-full min-h-screen dark:text-white">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image src={Pic} alt="CB" className="w-full h-auto lg:hidden md:inline-block md:w-full" priority sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"/>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Tutored Outfits"
                className="!text-5xl xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-sm">
                We are a cloth store where you can find what you are looking
                for.
              </p>
              <div className="flex items-center self-center mt-2 lg:self-center">
                <Link
                  href="/Contact"
                  className="flex items-center bg-black text-white p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-white hover:text-black border border-solid border-transparent hover:border-black dark:bg-white dark:text-black hover:dark:bg-black hover:dark:text-white hover:dark:border-white
                  md:p-2 md:px-4 md:text
                  "
                >
                  Contact Us <LinkArrow className={"w-4 ml-1 xl:w-16 xl:h-16 xl:p-2 lg:w-12 lg:h-12 lg:p-1 md:w-10 md:h-10 md:p-1 sm:w-8 sm:h-8 sm:p-1 xs:w-6 xs:h-6 xs:p-1"}/>
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
