import { useState, useEffect } from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Pic1 from "../../public/images/website-images/Pic3.jpeg";
import Pic2 from "../../public/images/website-images/Pic5.jpeg";
import Pic3 from "../../public/images/website-images/Pic9.jpeg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import { motion, AnimatePresence } from "framer-motion";
import Transition from "@/components/Transition";

const images = [Pic1, Pic2, Pic3];

export default function Home() {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon_io/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon_io/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon_io/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon_io/site.webmanifest"></link>
      </Head>
      <Transition />
      <main className="flex items-center text-black w-full min-h-screen dark:text-white">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <AnimatePresence mode="wait">
                <motion.div
                  key={currentImageIndex}
                  initial={{ x: 30, opacity: 0 }}
                  animate={{ x: [100, 20, 10], opacity: 1 }}
                  exit={{ x: -30, opacity: 0 }}
                  transition={{ duration: 1, ease: "easeInOut" }}
                >
                  <Image
                    src={images[currentImageIndex]}
                    alt="Home Pic"
                    className="w-[70%] h-[70%] my-10 lg:ml-32 lg:hidden md:inline-block md:h-[80%] md:w-[80%] md:mx-6 md:my-12 rounded-xl md:rounded-2xl"
                  />
                </motion.div>
              </AnimatePresence>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Tutored Outfits"
                className="!text-5xl xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl xs:!text-2xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-sm">
                Timeless pieces for the Modern Woman.
              </p>
              <div className="flex items-center self-center mt-2 lg:self-center">
                <Link
                  href="/Contact"
                  className="flex items-center bg-black text-white p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-white hover:text-black border border-solid border-transparent hover:border-black dark:bg-white dark:text-black hover:dark:bg-black hover:dark:text-white hover:dark:border-white
                  md:p-2 md:px-4 md:text
                  "
                >
                  Contact Us{" "}
                  <LinkArrow
                    className={
                      "w-4 ml-1 xl:w-16 xl:h-16 xl:p-2 lg:w-12 lg:h-12 lg:p-1 md:w-10 md:h-10 md:p-1 sm:w-8 sm:h-8 sm:p-1 xs:w-6 xs:h-6 xs:p-1"
                    }
                  />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
